name: drake
version: 0.4.0-dev
author: devoncarew@google.com
description: A Chrome app based web development environment
dependencies:
  compiler_unsupported: any
  analyzer_experimental: any
  browser: any
  chrome: any
  js: any
  path: any
  args: any
  unittest: any
